import { 
  UtensilsCrossed, 
  Building, 
  Laptop, 
  HeartPulse, 
  GraduationCap, 
  ShoppingBag, 
  HardHat, 
  Car, 
  CreditCard, 
  Plane, 
  Sparkles, 
  Truck,
  Users,
  Briefcase,
  Wrench,
  Stethoscope,
  Scissors,
  Home
} from 'lucide-react'

export const CATEGORY_ICONS: Record<string, any> = {
  'home-services': Wrench,
  'professional-services': Briefcase,
  'health-wellness': Stethoscope,
  'healthcare': HeartPulse,
  'restaurants-food': UtensilsCrossed,
  'restaurants': UtensilsCrossed,
  'automotive': Car,
  'beauty-personal-care': Scissors,
  'beauty': Sparkles,
  'education': GraduationCap,
  'technology': Laptop,
  'local-services': Building,
  'real-estate': Building,
  'retail': ShoppingBag,
  'construction': HardHat,
  'finance': CreditCard,
  'travel': Plane,
  'logistics': Truck,
  'pets-animals': Sparkles,
  'legal-services': Briefcase,
  'cleaning-maintenance': Wrench,
  'events-weddings': Sparkles,
  'business-finance-professionals': CreditCard,
  'design-creative': Sparkles,
  'education-professionals': GraduationCap,
  'healthcare-professionals': HeartPulse,
  'legal-professionals': Briefcase,
  'marketing-professionals': Sparkles,
  'skilled-trades': HardHat,
  'technology-professionals': Laptop,
  'professional-job-seeker': Users,
  'professionals': Users,
  'hiring-company-hr': Briefcase,
  'companies': Briefcase,
  'other': Briefcase,
}

export const CATEGORY_GRADIENTS: Record<string, string> = {
  'home-services': 'from-sky-500 to-blue-600',
  'professional-services': 'from-indigo-500 to-purple-600',
  'health-wellness': 'from-rose-500 to-red-600',
  'healthcare': 'from-rose-500 to-red-600',
  'restaurants-food': 'from-amber-500 to-orange-600',
  'restaurants': 'from-amber-500 to-orange-600',
  'automotive': 'from-teal-500 to-emerald-600',
  'beauty-personal-care': 'from-fuchsia-500 to-pink-600',
  'beauty': 'from-fuchsia-500 to-pink-600',
  'education': 'from-violet-500 to-purple-600',
  'technology': 'from-blue-500 to-cyan-600',
  'local-services': 'from-slate-500 to-gray-700',
  'real-estate': 'from-emerald-500 to-teal-600',
  'retail': 'from-pink-500 to-rose-600',
  'construction': 'from-amber-600 to-orange-700',
  'finance': 'from-indigo-600 to-blue-700',
  'travel': 'from-cyan-500 to-blue-600',
  'logistics': 'from-lime-600 to-green-700',
  'pets-animals': 'from-emerald-500 to-teal-600',
  'legal-services': 'from-indigo-500 to-purple-600',
  'cleaning-maintenance': 'from-cyan-500 to-blue-600',
  'events-weddings': 'from-pink-500 to-rose-600',
  'business-finance-professionals': 'from-indigo-600 to-blue-700',
  'design-creative': 'from-pink-500 to-purple-600',
  'education-professionals': 'from-violet-500 to-purple-600',
  'healthcare-professionals': 'from-rose-500 to-red-600',
  'legal-professionals': 'from-indigo-500 to-purple-600',
  'marketing-professionals': 'from-amber-500 to-orange-600',
  'skilled-trades': 'from-amber-600 to-orange-700',
  'technology-professionals': 'from-blue-500 to-cyan-600',
  'professional-job-seeker': 'from-blue-600 to-indigo-700',
  'professionals': 'from-blue-600 to-indigo-700',
  'hiring-company-hr': 'from-sky-600 to-blue-700',
  'companies': 'from-sky-600 to-blue-700',
}

export const CATEGORY_BG_COLORS: Record<string, string> = {
  'home-services': 'bg-sky-50 text-sky-700 border-sky-100',
  'professional-services': 'bg-indigo-50 text-indigo-700 border-indigo-100',
  'health-wellness': 'bg-rose-50 text-rose-700 border-rose-100',
  'healthcare': 'bg-rose-50 text-rose-700 border-rose-100',
  'restaurants-food': 'bg-amber-50 text-amber-700 border-amber-100',
  'restaurants': 'bg-amber-50 text-amber-700 border-amber-100',
  'automotive': 'bg-teal-50 text-teal-700 border-teal-100',
  'beauty-personal-care': 'bg-pink-50 text-pink-700 border-pink-100',
  'beauty': 'bg-pink-50 text-pink-700 border-pink-100',
  'education': 'bg-purple-50 text-purple-700 border-purple-100',
  'technology': 'bg-blue-50 text-blue-700 border-blue-100',
  'local-services': 'bg-slate-50 text-slate-700 border-slate-200',
  'real-estate': 'bg-emerald-50 text-emerald-700 border-emerald-100',
  'retail': 'bg-pink-50 text-pink-700 border-pink-100',
  'construction': 'bg-orange-50 text-orange-700 border-orange-100',
  'finance': 'bg-indigo-50 text-indigo-700 border-indigo-100',
  'travel': 'bg-sky-50 text-sky-700 border-sky-100',
  'logistics': 'bg-lime-50 text-lime-700 border-lime-100',
  'pets-animals': 'bg-emerald-50 text-emerald-700 border-emerald-100',
  'legal-services': 'bg-indigo-50 text-indigo-700 border-indigo-100',
  'cleaning-maintenance': 'bg-cyan-50 text-cyan-700 border-cyan-100',
  'events-weddings': 'bg-pink-50 text-pink-700 border-pink-100',
  'business-finance-professionals': 'bg-indigo-50 text-indigo-700 border-indigo-100',
  'design-creative': 'bg-purple-50 text-purple-700 border-purple-100',
  'education-professionals': 'bg-purple-50 text-purple-700 border-purple-100',
  'healthcare-professionals': 'bg-rose-50 text-rose-700 border-rose-100',
  'legal-professionals': 'bg-indigo-50 text-indigo-700 border-indigo-100',
  'marketing-professionals': 'bg-orange-50 text-orange-700 border-orange-100',
  'skilled-trades': 'bg-amber-50 text-amber-700 border-amber-100',
  'technology-professionals': 'bg-blue-50 text-blue-700 border-blue-100',
  'professional-job-seeker': 'bg-blue-50 text-blue-700 border-blue-100',
  'professionals': 'bg-blue-50 text-blue-700 border-blue-100',
  'hiring-company-hr': 'bg-sky-50 text-sky-700 border-sky-100',
  'companies': 'bg-sky-50 text-sky-700 border-sky-100',
}
